### ISSUE TITLE
Support Resold WHM Reseller

### ISSUE THREAD

**Issue by sdelemos** [upmind-automation/provision-provider-shared-hosting#14]
If User X wants to provide a WHM reseller to their user, and they don't have a server with root access, they may buy a standalone reseller account and just want to provide details to their own client with login functionality.

We could handle this in two ways:
- A standalone provider to allow someone 'resell' a whole WHM reseller account to their own clients.
- Adding the reseller as a provision configuration itself, and allowing the client to use this directly

The only functionality that should work is 
- Login to control panel
- Change password

Upgrade/downgrade will not work, and Suspend/Terminate would remove the whole account. 

This also needs to come with a warning - as it the end client logged into whm and for example wiped the api tokens and changed the password, it could remove complete access from the user

**Comment by uphlewis** [comment]
I'm not sure whether this needs a separate provider as could be implemented in the blueprint layer in Upmind
