### ISSUE TITLE
No roadmap and when i asked in ticket i was sent here

### ISSUE THREAD

**Issue by ThunderM16** [upmind-automation/provision-provider-shared-hosting#16]
No roadmap and when i asked in ticket i was sent here, You guys don't have a project roadmap you have no roadmap on your site you have no explaining whats being worked on whats been done and whats going to be done I've attempted to make tickets asking many times towards upmind and seems going publicly is the only way to properly have this matter resolved.
I asked if vultr and digitalocean is to be incorporated I was told to keep a eye out  here over the next few weeks in regards to the question, but as I stated there is no roadmap or anything to let end-clients /companies KNOW whats happening on your guys end and if there is it should be provided on your github then as well properly
![image](https://user-images.githubusercontent.com/70344872/190269057-f3266422-bfaa-4e51-88e5-0ee161c3d3ea.png)

**Comment by uphlewis** [comment]
Work on a servers category starts this week. DO and Vultr issues have been created on that project:
https://github.com/upmind-automation/provision-provider-servers/issues/2
https://github.com/upmind-automation/provision-provider-servers/issues/3
