### ISSUE TITLE
Update getLoginUrl()

### ISSUE THREAD

**Issue by uphlewis** [upmind-automation/provision-provider-shared-hosting#37]
This is driven by the desire to fake SSO for SolidCP which does not officially support it. Integrations on other platforms store the account password and do a simple browser post to the login form with the stored credentials. We can get similar behaviour with a couple of changes:

- Update GetLoginUrlParams to optionally accept `current_password` (nullable)
- In SolidCP getLoginUrl() if `current_password` is **not** passed, change the account password to something random
- Update LoginUrl result data to support an optional `post_fields` array
- Update SolidCP getLoginUrl() to return the username + current password in `post_fields` with the correct keys for the SolidCP login form

**Comment by AnaGema** [comment]
Implemented the functionality.


Uploading Screen Recording 2023-12-19 at 14.49.01.mov…
