### ISSUE TITLE
Add support for Enhance's new multiple location for the same package feature

### ISSUE THREAD

**Issue by mendozal** [upmind-automation/provision-provider-shared-hosting#39]
In the latest 10.0 update, Enhance added the ability to allow customers to select the location where their website/service will be created, using the same package. 

This works from the Enhance admin area, when clients manually create their websites. But considering Upmind provisions the first website, it would be nice to have the ability to select where to create it.

`Ability to create 'location based' hosting packages, with the user having a choice of location at the point of adding a website.
`
This is the docs entry for this feature: https://enhance.com/docs/packages/create-location-based-hosting-packages.html

They said everything is exposed in the API, so it should be possible to add support.

I noticed you're adding support for a similar feature for 20i:
https://github.com/upmind-automation/provision-provider-shared-hosting/issues/4

Please consider adding this.

**Comment by uphlewis** [comment]
Thanks Luis yes great timing with #4 - we'll look into it!

**Comment by uphlewis** [comment]
Hi Luis, the only way of us adding support for this right now would be if you replicated the server group ids as product attributes in your Upmind product catalogue for each plan. Would be more straight-forward if there was a provision configuration value which turns off creation of the first website when provisioning a new enhance hosting account? That way the customer can log into their enhance dashboard and create their first website from there.

What are your thoughts?

**Comment by mendozal** [comment]
Hi Harry.

The ability to disable first website creation is very interesting, considering one service/package can give you the ability to create multiple websites, not only one. We could inform client's via email how the can create their websites afterwards.

About the other option, is not that bad having to create the locations as product attributes. I believe we could even create a product attribute category called "Location" and present that to users. And even add a little fee depending on selected location. 

I just don't know how much effort would any of this imply for you.

Regards.
