### ISSUE TITLE
Enhance new package location selector

### ISSUE THREAD

**Issue by ismaaffiya** [upmind-automation/provision-provider-shared-hosting#44]
Support Enhance's new package location selection integration so that customers can select a location during checkout that corresponds to the location in Enhance when adding a service

**Comment by qublify** [comment]
Hi, any updates on this? Would be ideal if this could be supported ASAP.

**Comment by clearhost-cmd** [comment]
We need this ASAP our customers cannot select locations currently!

**Comment by mendozal** [comment]
If would be great if this feature is supported in the Upmind-Enhance integration.

**Comment by uphlewis** [comment]
Duplicate of #39
