### ISSUE TITLE
Add enhance provision configuration value to not create website

### ISSUE THREAD

**Issue by uphlewis** [upmind-automation/provision-provider-shared-hosting#46]
Related to #39 

The idea is that when a customer places an order, if this value is enabled in the provision configuration then only the subscription would be created (not the website) which gives the customer the freedom to log in and create their website through the Enhance UI, taking advantage of the available server groups etc configured in Enhance so this doesn't need to be replicated as product attributes in Upmind.

**Comment by mendozal** [comment]
I'm not sure if less tech-savvy customers with only one website would find this easy to do. It might be simpler for them to directly choose the location in Upmind, at least for the first website.

I've reached out to other members of the Enhance community for their input on this matter.

**Comment by uphlewis** [comment]
> I'm not sure if less tech-savvy customers with only one website would find this easy to do. It might be simpler for them to directly choose the location in Upmind, at least for the first website (in case their subscription allows more than 1).
> 
> I've reached out to other members of the Enhance community for their input on this matter.

Thanks for the insight, great points.

The proposed behaviour here is simple to implement and would work as an alternative to businesses needing to configure product attributes to mirror the server/groups setup in Enhance. The default behaviour would still be to create the website at the same time as the subscription.
