### ISSUE TITLE
Directadmin needs notify new user

### ISSUE THREAD

**Issue by jimsefton** [upmind-automation/provision-provider-shared-hosting#58]
When a new account is created the user should receive an email with their account details. I believe this is done via the notify value on the DirectAdmin API. Seems like this is not being set.

**Comment by uphlewis** [comment]
Thanks for the suggestion @jimsefton - we just released a new version of the library with some DirectAdmin improvements, including enabling notifications from DA upon account creation which you can enable in your provision configuration in Upmind.

https://github.com/upmind-automation/provision-provider-shared-hosting/compare/v6.6.7...v6.6.9
